development:
  host: <%= ENV['MONGOID_HOST'] ||= "localhost" %>
  database: govuk_assets_development
  persist_in_safe_mode: true

test:
  host: <%= ENV['MONGOID_HOST'] ||= "localhost" %>
  database: govuk_assets_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
